version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/document-webhook-service-1

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
